Pendulum Problem added
JuliaPlots/PlotDocs.jl pull request #298
Opened 2022-09-07 11:41 UTC by Dietzlix

Hey,

look at my nice changes! 
I have translated the pendulum problem from: 
https://matplotlib.org/stable/gallery/animation/double_pendulum.html#sphx-glr-gallery-animation-double-pendulum-py
and added the file to the user_gallery/misc folder.

2022-09-07 12:21 UTC, t-bltg commented on docs/user_gallery/misc/Pendulum.jl
> +       plot!(ylims=(-2,1),yticks=-2:0.5:1)
```suggestion
       plot!(xlims=(-2,2), xticks=-2:0.5:2)
       plot!(ylims=(-2,1), yticks=-2:0.5:1)
```

2022-09-07 12:21 UTC, t-bltg commented on docs/user_gallery/misc/Pendulum.jl
> +gif(anim, "assets/Pendulum.gif", fps=10) #src
```suggestion
gif(anim, "assets/Pendulum.gif", fps=10) #src

```

2022-09-07 12:22 UTC, t-bltg commented on docs/user_gallery/misc/Pendulum.jl
> +       y = [0,y1[i],y2[i]]
```suggestion
       x = [0, x1[i], x2[i]]
       y = [0, y1[i], y2[i]]
```

2022-09-07 12:22 UTC, t-bltg commented on docs/user_gallery/misc/Pendulum.jl
> +y2 = -L2*cos.(sol[3, :]) + y1
```suggestion
x1 = +L1 * sin.(sol[1, :])
y1 = -L1 * cos.(sol[1, :])

x2 = +L2 * sin.(sol[3, :]) + x1
y2 = -L2 * cos.(sol[3, :]) + y1
```

2022-09-07 12:23 UTC, t-bltg commented on docs/user_gallery/misc/Pendulum.jl
> +    den1 = (M1+M2) * L1 - M2 * L1 * cos(delta) * cos(delta)
```suggestion
    den1 = (M1 + M2) * L1 - M2 * L1 * cos(delta) * cos(delta)
```

2022-09-07 12:23 UTC, t-bltg commented on docs/user_gallery/misc/Pendulum.jl
> +    den2 = (L2/L1) * den1
```suggestion
    den2 = (L2 / L1) * den1
```

2022-09-07 12:23 UTC, t-bltg commented
Please use a consistent formatting.

2022-09-07 12:24 UTC, t-bltg commented on docs/user_gallery/misc/Pendulum.jl
> +                - (M1+M2) * G * sin(u[3]))
```suggestion
                + (M1 + M2) * G * sin(u[1]) * cos(delta)
                - (M1 + M2) * L1 * u[2] * u[2] * sin(delta)
                - (M1 + M2) * G * sin(u[3]))
```

2022-09-07 12:25 UTC, johnnychen94 commented on docs/user_gallery/misc/Pendulum.jl
> +
> I have translated the pendulum problem from:
https://matplotlib.org/stable/gallery/animation/double_pendulum.html#sphx-glr-gallery-animation-double-pendulum-py

It would be much nicer if we make it clear that it comes from another framework. (properly acknowledge people's efforts). How about

```suggestion
# This animation illustrates the double pendulum problem.

# Double pendulum formula translated from the [matplotlib gallery](https://matplotlib.org/stable/gallery/animation/double_pendulum.html#sphx-glr-gallery-animation-double-pendulum-py).
```

2022-09-07 12:28 UTC, johnnychen94 commented on docs/user_gallery/misc/Pendulum.jl
> +using OrdinaryDiffEq
I _think_ we'll need to add this to `docs/Project.toml`

2022-09-07 13:44 UTC, t-bltg commented on docs/Project.toml
> +UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"
Please restore the trailing newline.

2022-09-07 13:48 UTC, t-bltg commented on docs/user_gallery/misc/Pendulum.jl
> +               / den2)
```suggestion
    du[4] = (
        - M2 * L2 * u[4]^2 * sin(delta) * cos(delta) +
        (M1 + M2) * G * sin(u[1]) * cos(delta) -
        (M1 + M2) * L1 * u[2]^2 * sin(delta) -
        (M1 + M2) * G * sin(u[3])
    ) / den2
```

2022-09-07 13:51 UTC, t-bltg commented on docs/user_gallery/misc/Pendulum.jl
> +       plot(x, y, legend = false)
```suggestion
       plot(x, y, legend=false)
```

Again inconsistent spacing.

2022-09-07 13:51 UTC, t-bltg commented on docs/user_gallery/misc/Pendulum.jl
> +       plot!(ylims=(-2,1), yticks=-2:0.5:1)
```suggestion
       plot!(xlims=(-2, 2), xticks=-2:0.5:2)
       plot!(ylims=(-2, 1), yticks=-2:0.5:1)
```

2022-09-07 13:51 UTC, t-bltg commented on docs/user_gallery/misc/Pendulum.jl
> +       plot!(ylims=(-2,1), yticks=-2:0.5:1)
```suggestion
       plot!(xlims=(-2, 2), xticks=-2:0.5:2)
       plot!(ylims=(-2, 1), yticks=-2:0.5:1)
```

2022-09-07 13:52 UTC, t-bltg commented on docs/user_gallery/misc/Pendulum.jl
> +       plot!(x, y, linecolor = :orange)
```suggestion
       plot!(x, y, linecolor=:orange)
```

2022-09-07 13:55 UTC, t-bltg requested changes
Please use some kind of formatter for consistency.

2022-09-08 09:39 UTC, t-bltg approved these changes

2022-09-08 11:04 UTC, merged